/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package DataMusik;

/**
 *
 * @author HP
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.persistence.*;

public class InsertDlgMusik extends javax.swing.JDialog {

    private Utama utama;
    private DefaultTableModel model; // simpan model dari parent
    private boolean saved = false;

    /**
     * Creates new form InsertDlgMusik
     */
    public InsertDlgMusik(java.awt.Frame parent, boolean modal, Utama utama) {
        super(parent, modal);
        initComponents();
        this.utama = utama; // simpan referensi agar tidak null
    }

    public InsertDlgMusik(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null);
    }

    public boolean isSaved() {
        return saved;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlInputkanData = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        jlJudul = new javax.swing.JLabel();
        jlArtis = new javax.swing.JLabel();
        tfIdLagu = new javax.swing.JTextField();
        tfJudul = new javax.swing.JTextField();
        tfArtis = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jlID1 = new javax.swing.JLabel();
        tfIdAlbum = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 191, 220));

        jlInputkanData.setFont(new java.awt.Font("Baloo", 0, 24)); // NOI18N
        jlInputkanData.setText("INPUTKAN DATA MUSIK");

        jlID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlID.setText("ID Lagu");

        jlJudul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlJudul.setText("Judul");

        jlArtis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlArtis.setText("Artis");

        tfIdLagu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdLaguActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(173, 216, 240));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jlID1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlID1.setText("ID Album");

        tfIdAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdAlbumActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 153, 153));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlInputkanData)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlArtis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlID, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jlID1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfJudul)
                            .addComponent(tfArtis)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfIdLagu, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfIdAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(34, 34, 34))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClear, btnSave});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlInputkanData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlID)
                    .addComponent(tfIdLagu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlID1)
                    .addComponent(tfIdAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlJudul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlArtis)
                    .addComponent(tfArtis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addGap(70, 70, 70))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClear, btnSave});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdLaguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdLaguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdLaguActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (tfIdLagu.getText().equals("") || tfIdAlbum.getText().equals("")
                || tfJudul.getText().equals("") || tfArtis.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu!");
        } else {
            String idMusik = tfIdLagu.getText();
            String idAlbum = tfIdAlbum.getText();
            String judul = tfJudul.getText();
            String artis = tfArtis.getText();

            try {
                // Buat koneksi persistence
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBOPertemuanDuabelasPU");
                EntityManager em = emf.createEntityManager();
                em.getTransaction().begin();

                // 🔹 Ambil entitas album berdasarkan ID (karena FK)
                Album album = em.find(Album.class, idAlbum);
                if (album == null) {
                    JOptionPane.showMessageDialog(null,
                            "ID Album tidak ditemukan di database!",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    em.close();
                    emf.close();
                    return;
                }

                // 🔹 Validasi 1 — Cek apakah ID Lagu sudah digunakan (Primary Key)
                Musik existing = em.find(Musik.class, idMusik);
                if (existing != null) {
                    JOptionPane.showMessageDialog(null,
                            "ID Lagu sudah digunakan! Gunakan ID lain.",
                            "Duplikat ID Lagu", JOptionPane.WARNING_MESSAGE);
                    em.close();
                    emf.close();
                    return;
                }

                // 🔹 Validasi 2 — Cek apakah lagu dengan judul & artis sama sudah ada di album yang sama
                Query q = em.createQuery(
                        "SELECT COUNT(m) FROM Musik m WHERE m.judul = :judul AND m.artis = :artis AND m.idAlbum = :album"
                );
                q.setParameter("judul", judul);
                q.setParameter("artis", artis);
                q.setParameter("album", album);
                long count = (long) q.getSingleResult();

                if (count > 0) {
                    JOptionPane.showMessageDialog(null,
                            "Lagu dengan judul dan artis yang sama sudah ada di album ini!",
                            "Duplikat Lagu", JOptionPane.WARNING_MESSAGE);
                    em.close();
                    emf.close();
                    return;
                }

                // Buat object JadwalTayang
                Musik musik = new Musik();
                musik.setIdMusik(idMusik);
                musik.setIdAlbum(album);   // relasi FK ke entitas Album
                musik.setJudul(judul);
                musik.setArtis(artis);

                // Simpan ke database
                em.persist(musik);
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(null, "Data musik berhasil disimpan!");

                // Bersihkan field input
                bersih();

                // Refresh tabel di JFrame (pastikan ada method showTableJadwal di JFrame)
                utama.showTableMusik();

                em.close();
                emf.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Terjadi kesalahan saat menyimpan data: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tfIdAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdAlbumActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        bersih();
    }//GEN-LAST:event_btnClearActionPerformed

    private void bersih() {
        tfIdLagu.setText("");
        tfIdAlbum.setText("");
        tfJudul.setText("");
        tfArtis.setText("");
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgMusik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgMusik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgMusik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgMusik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                InsertDlgMusik dialog = new InsertDlgMusik(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlArtis;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlID1;
    private javax.swing.JLabel jlInputkanData;
    private javax.swing.JLabel jlJudul;
    private javax.swing.JTextField tfArtis;
    private javax.swing.JTextField tfIdAlbum;
    private javax.swing.JTextField tfIdLagu;
    private javax.swing.JTextField tfJudul;
    // End of variables declaration//GEN-END:variables
}
